### ISSUE TITLE
repoq doesn't check if repo is currently online

### ISSUE THREAD

**Issue by drpaneas** [openSUSE/repose#1]
It doesn't check if the repo is accessible (_e.g._ maybe the server is down, or the URL is wrong). I assume this because the the patchlevel (Service Pack) variable is created through some pattern and there's no checking whether such SP exists or not. As a result the tool is susceptible to return wrong (fake) links.

```
$ repoq -a x86_64 sles:12.666
sles:12.666::gm http://download.suse.de/ibs/SUSE/Products/SLE-SERVER/12-SP666/x86_64/product/
sles:12.666::up http://download.suse.de/ibs/SUSE/Updates/SLE-SERVER/12-SP666/x86_64/update/
sles:12.666::dg http://download.suse.de/ibs/SUSE/Products/SLE-SERVER/12-SP666/x86_64/product_debug/
sles:12.666::du http://download.suse.de/ibs/SUSE/Updates/SLE-SERVER/12-SP666/x86_64/update_debug/
```

In the above example, I have the links for SLE-SERVER 12 Service Pack _666_; Apparently this is wrong. I see two issues here:

1. there's no rule for checking if the patchlevel exists or not
2. no check if the link is online/accessible at the requested time.

If I may I would like to propose a solution for the (2) issue, something like a _flag/switch_ that does gives you only the current accessible repos. See the following example:

**Request wrong patchlevel**
`for repo in `repoq -N -a x86_64 sles:12.666`; do if curl --output /dev/null --silent --head --fail $repo; then echo "$repo"; fi; done`

this returns nothing. Expected behavior.

**Request working patchlevel**

`for repo in `repoq -N -a x86_64 sles:12.1`; do if curl --output /dev/null --silent --head --fail $repo; then echo "$repo"; fi; done`

this returns the following links, as expected:

```
http://download.suse.de/ibs/SUSE/Products/SLE-SERVER/12-SP1/x86_64/product/
http://download.suse.de/ibs/SUSE/Updates/SLE-SERVER/12-SP1/x86_64/update/
http://download.suse.de/ibs/SUSE/Products/SLE-SERVER/12-SP1/x86_64/product_debug/
http://download.suse.de/ibs/SUSE/Updates/SLE-SERVER/12-SP1/x86_64/update_debug/
```

**Comment by mimi1vx** [comment]
fixed in PR#15 , but in another way -- repoq returns all possible variants and repose check before adding repository to the host if repo exist's

**Comment by roman-neuhauser** [comment]
as i said elsewhere, this breaks repose in the case where the repo is visible from the target host but not the local host, which is (or at least was) quite common in testing suse-cloud.

**Comment by roman-neuhauser** [comment]
ah, ok, saw your reply just now.
