### ISSUE TITLE
Output yaml from repose scanning of products

### ISSUE THREAD

**Issue by plusky** [openSUSE/repose#101]
Currently we have:
```
repose list-products -t bragi.qam.suse.de
info: Connecting to bragi.qam.suse.de:22
Host: bragi.qam.suse.de:22
  Base product: SLES-15-x86_64
  Installed Extensions and Modules:
      Addon: sle-module-legacy                                     - version: 15
      Addon: sle-module-public-cloud                               - version: 15
      Addon: sle-module-desktop-applications                       - version: 15
      Addon: sle-module-server-applications                        - version: 15
      Addon: sle-module-development-tools                          - version: 15
      Addon: sle-module-web-scripting                              - version: 15
      Addon: sle-we                                                - version: 15
      Addon: sle-module-basesystem                                 - version: 15
      Addon: qa                                                    - version: 15
      Addon: sle-module-containers                                 - version: 15
      Addon: sle-module-live-patching                              - version: 15

```

It would be nice to have also yaml as used by refdb.yml via something like `repose list-products --yaml -t reference.host`

**Comment by mimi1vx** [comment]
New yaml format for  referencehost.yml base data  generated by repose:
---
name: fqdn
product:
  name: sles..
  version:
    major: 12..
    minor: sp3 # not for GA versions
addons:
  - name: sdk #etc
    version:
      major: 12
      minor: sp3 # not for GA and unversioned addons
location: # can be more locations , by repose only template
  - FIXME
arch: architecture
owner: # optional, not generated by repose
  - FIXME
virtual: # optional, not generated by repose 
  hypervisor:
  mode:
  host:
description: # optional, not generated by repose
....
