### ISSUE TITLE
issue-add returns 0 in case of failure

### ISSUE THREAD

**Issue by drpaneas** [openSUSE/repose#2]
In the following _example_ I am trying (_on purpose_) to _add_ SLES _specific repositories_ in a SLED host.

`pgeorgiadis@panos:~/qam/templates/SUSE:Maintenance:xxxx:xxxxx> repose issue-add root@tux.qam.suse.de -- .`

There's no any feedback/notification mechanism to inform the user that the previous command failed. I had to _ssh_ into the host and check the repos in order to verify that the previous command **didn't** actually worked.

Also, the return code is also wrong:

```
pgeorgiadis@panos:~/qam/templates/SUSE:Maintenance:xxxx:xxxxx> echo $?
0
```

TODO:
1. print a human friendly warning message in case of failure
2. return a non-zero signal.

**Comment by roman-neuhauser** [comment]
a single host and a single issue is a (most common but still) corner case.  what should happen if only some host / issue combinations yield no urls?

**Comment by drpaneas** [comment]
This is basically the typical -- default -- scenario for minimal testing preparation. In a matter of fact, the procedure of configuring individual hosts _one-by-one_ is a very common work-flow. If the tool cannot provide reasonable feedback in case of failure, it's easier for me to use the `-n` option.


> -n, --print
> Write destructive operations to standard output, do not actually perform them.

In that way, I will fetch the `zypper addrepo` commands and then _manually_ run them _directly_ on the ref-host. Why, _you may ask_, this is simply because I value that feedback more than speed/confort. So, if there's a way to catch any potential error message on run-time, I would go for it.


From the other hand, if the tool cannot provide me reliable feedback on a _single host -- single issue_ scenario, how should I suppose to handle a scenario of _multiple hosts - single issue_ (also very common).

Since you asked, I would expect the output to be something similar to this:

```
repose issue-add root@[hostA,hostB].suse.de -- .

repo X was unable to be added in hostA.suse.de -> return code -1
repo Y added successfully in hostA.suse.de -> return code 0
repo Z added successfully in hostA.suse.de -> return code 0
repo X was unable to be added in hostB.suse.de -> return code -1
repo Y added successfully in hostB.suse.de -> return code 0
repo Z was unable to be added in hostB.suse.de -> return code -1


There were some errors. To fix them please try again to manually the add the repositories to their hosts respectively:

 hostA.suse.de : 
  - zypper -n ar -cgkn repoX 
 hostB.suse.de: 
  - zypper -n ar -cgkn repoX
  - zypper -n ar -cgkn repoZ

```

**Comment by roman-neuhauser** [comment]
a single host and a single issue is a (most common but still) corner case.  what should happen if only some host / issue combinations yield no urls?

**Comment by mimi1vx** [comment]
dependency on repose issue* commands was removed from MTUI
