### ISSUE TITLE
repose-reset should add additional repositories for some products

### ISSUE THREAD

**Issue by plusky** [openSUSE/repose#21]
When `repose-reset` there are several cases when repositories that are/can/should be added for product are not added:
-  for SLED ati/nvidia
-  SLES for SAP installs HA (on SLE-11)

**Comment by drpaneas** [comment]
for SLED 12 SP2:

- NVIDIA: http://http.download.nvidia.com/novell/sle12sp2
- ATI: does not exist yet :/

**Comment by plusky** [comment]
Hmm and there are nv repos for Leap as well

**Comment by plusky** [comment]
Fixed by commit #58
