### ISSUE TITLE
Add openQA repositories to rules

### ISSUE THREAD

**Issue by vpelcak** [openSUSE/repose#46]
Please add this rule for the future usage of openQA deployment.

**Comment by mimi1vx** [comment]
@vpelcak ? which rule?

**Comment by vpelcak** [comment]
Sorry, I meant REPA (repository pattern).

Something like:
repose install root@snafu -- openqa

**Comment by vpelcak** [comment]
Sorry, I meant REPA (repository pattern).

Something like:
repose install root@snafu -- openqa

**Comment by plusky** [comment]
All product/repo logic/definitions were moved to refhosts.yml - not a repose issue anymore
