### ISSUE TITLE
no rules for SLES_RPI product

### ISSUE THREAD

**Issue by drpaneas** [openSUSE/repose#57]
I've recently set up a _RPi3_ with _SUSE Linux Enterprise Server 12-SP2 for the Raspberry Pi_ and I've tried and failed to setup its repositories using _repose_.

```
repose reset root@g110.suse.de
repoq: no rule matches 'sles_rpi:12.2
```

This is true, because:

**A**: the product in the host is indeed _SLES_RPI_. See below:

```
linux:~ # zypper products -i
Loading repository data...
Reading installed packages...
S | Repository | Internal Name | Name                                              | Version | Arch    | Is Base
--+------------+---------------+---------------------------------------------------+---------+---------+--------
i | @System    | SLES_RPI      | SUSE Linux Enterprise Server for the Raspberry Pi | 12.2-0  | aarch64 | Yes
```

and

```
linux:~ # ls -l /etc/products.d/*.prod
-rw-r--r-- 1 root root 2995 Sep 29 17:31 /etc/products.d/SLES_RPI.prod
```

**B**: we don't have any repositories for this product in repoq:

```
# repoq -a aarch64 sles-rpi:12.2
repoq: no rule matches 'sles-rpi:12.2'
```

However, we do have repositories for _sles-sp2_ and _aarch64_. 

```
# repoq -a aarch64 sles:12.2
                                                                                                                                                 sles:12.2::gm http://download.suse.de/ibs/SUSE/Products/SLE-SERVER/12-SP2/aarch64/product/
sles:12.2::up http://download.suse.de/ibs/SUSE/Updates/SLE-SERVER/12-SP2/aarch64/update/
sles:12.2::dg http://download.suse.de/ibs/SUSE/Products/SLE-SERVER/12-SP2/aarch64/product_debug/
sles:12.2::du http://download.suse.de/ibs/SUSE/Updates/SLE-SERVER/12-SP2/aarch64/update_debug/
sles:12.2::lt http://download.suse.de/ibs/SUSE/Updates/SLE-SERVER/12-SP2-LTSS/aarch64/update/
sles:12.2::dl http://download.suse.de/ibs/SUSE/Updates/SLE-SERVER/12-SP2-LTSS/aarch64/update_debug/
```

Are these the correct ones? If yes, I would suggest to create a new product in the rules for  _SLES_RPI_ and add them into it.

**Comment by plusky** [comment]
Hmm this is new, images we had were using SLE product, but as updates for rpi will be provided in special channel it makes sense

**Comment by drpaneas** [comment]
I also see that we have new repositories for that as well, so before creating it it will make sense to check and put the correct repositories there. For instance look here:

http://download.suse.de/ibs/SUSE/Updates/SLE-RPI/12-SP2/aarch64/
