### ISSUE TITLE
repose reset doesn't add repos unless there's one that needs to be removed

### ISSUE THREAD

**Issue by drpaneas** [openSUSE/repose#6]
**How to reproduce:** setup a SLES 12 SP1 machine and remove any repositories.

```
# | Alias         | Name          | Enabled | GPG Check | Refresh | 
--+---------------+---------------+---------+-----------+---------+
1 | sles:12.1::gm | sles:12.1::gm | Yes     | (r ) Yes  | No      |
2 | sles:12.1::up | sles:12.1::up | Yes     | (r ) Yes  | No      |
```

now remove them:
`zypper rr 1 2`

Now ask _repose-reset_ to fix this:

```
repose reset -n root@10.160.65.227
(No output)
```

according to the manpage _description_:

> repose reset removes all package repositories except those that belong to an installed product, and adds missing repositories for installed products

 I would expect repose-reset to add the missing repos back. This didn't happen. So, I guess it's a bug.

**Workaround:** add a wrong repo and then try again.

I am going to add a completely unrelated repository to the system:

`zypper -n ar http://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Leap_42.1/ packman`

Now, I am trying again the very same command using _repose-reset_:

```
repose reset -n root@10.160.65.227
```

Output:
```
ssh -n -o BatchMode=yes root@10.160.65.227 zypper -n rr http://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Leap_42.1/
ssh -n -o BatchMode=yes root@10.160.65.227 zypper -n ar -cgkn sles:12.1::gm http://internal.suse.repository sles:12.1::gm
ssh -n -o BatchMode=yes root@10.160.65.227 zypper -n ar -cgkn sles:12.1::up http://internal.suse.repository sles:12.1::up
```

and it worked... :)

**Comment by roman-neuhauser** [comment]
@drpaneas what's the output of `REPOSE_CHATTY='*' repose reset -n root@10.160.65.227` (with and without the unrelated repository)?

**Comment by roman-neuhauser** [comment]
proper fix *and tests* for this: roman-neuhauser/repose@fb11fae288295fa5cc173dabb0e1421e0dbd2c0f

**Comment by mimi1vx** [comment]
unfortunately fix is only partial.. and tests isn't able to check real problem...

Source of problem is ```zypper -x lr``` on host without any repo, it returns EXITCODE 6. Whis is trapped by ```setopt err_return`` and run of repose is stoped after ttemp cleanup

--  so problem has two solutions..

hide real return code from zypper, or localy disable err_return
