### ISSUE TITLE
repository not refreshed after issue-add, leads to user action in automated environment

### ISSUE THREAD

**Issue by djz88** [openSUSE/repose#63]
When adding repository(for a first time - on new host)
`repose issue-add root@host.xe -- /PATH_TO_DIRECTORY_WITH_METADATA`

repository is not refreshed which can lead to situation that gpg key is not in trusted keys and when *zypper refresh* is run it will ask for an user action
>Do you want to reject the key, trust temporarily, or trust always? [r/t/a/? shows all options] (r): Cannot read input: bad stream or EOF.

If it is done automatically(via mtui for example), update of package will fail(as mentioned above).

Possible solution could be 

- add  command 
`"zypper --gpg-auto-import-keys refresh"`
  right after a repository are added in *repose-issue-add* like
`   77     for issue in $issues; do`
`   78       o sumaxy $issue:a $arch $products \`
`   79       | while read rn ru; do`
 `  80           run-in $h "zypper -n ar -cgkn $rn $ru $rn"`
 `+81           run-in $h "zypper -n --gpg-auto-import-keys refresh $rn"`
 `  82         done`

- change mtui command which is run after repose issue-add
`zypper refresh`
to
`zypper --gpg-auto-import-keys refresh `

- Or sth else :)

**Comment by plusky** [comment]
`run-in $h " zypper -n --gpg-auto-import-keys ar -cgkn $rn $ru $rn"` seems like a viable solution to me

**Comment by djz88** [comment]
I tried it but it didn t work for me. User interaction still wanted
