### ISSUE TITLE
repose-reset does not remove issue repositories

### ISSUE THREAD

**Issue by rwmanos** [openSUSE/repose#81]
repose-reset does not remove issue repositories.

Workaround: run first repose-clear and then repose-reset

**Comment by mimi1vx** [comment]
sh.. i See base of problem .. this will be non-trivial

**Comment by ktsamis** [comment]
So I just bumped into this again. It seems it is not fixed. I redacted some stuff, like hostname of the refhost used in the following example and the hostname of the mirror for the repositories. I am not sure if there is something left, if so, let me know. Reopening this to take a look. 

Version affected:
repose-0.26.1-1.1.noarch
Case where I bumped onto it:
[usecase.txt](https://github.com/openSUSE/repose/files/663751/paste.txt)

**Comment by mimi1vx** [comment]
@ktsamis  it was fixed by sumaxy, changed naming scheme for issue , for old remains of issue repository it must be cleared by `repose clear` or manually

**Comment by rwmanos** [comment]
> Resolved by https://github.com/openSUSE/sumaxy/pull/7
> 
> However, existing issue repositories and any in the form of "sles:11.4::p=3107" will not be removed. repose-clean should be used if necessary.

https://bugzilla.suse.com/show_bug.cgi?id=1014224#c2

**Comment by ktsamis** [comment]
Ok, so it was just leftovers from the old version that weren't cleared. So *sumaxy* should now understand and *repose reset* will clear the issue repos with the new naming scheme. I understand, thanks :)
